services:
  metastore:
    container_name: metastore
    hostname: metastore
    image: ghcr.io/orbitinghail/metastore:0.1.4
    stop_signal: SIGINT
    ports:
      - "3001:3001"
    networks:
      basic-net:
        ipv4_address: 10.20.20.10
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio-secret
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT=http://minio:9000
      - RUST_BACKTRACE=1

  pagestore:
    container_name: pagestore
    hostname: pagestore
    image: ghcr.io/orbitinghail/pagestore:0.1.4
    stop_signal: SIGINT
    ports:
      - "3000:3000"
    networks:
      basic-net:
        ipv4_address: 10.20.20.11
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio-secret
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT=http://minio:9000
      - PAGESTORE_METASTORE=http://metastore:3001
      - RUST_BACKTRACE=1

  minio:
    container_name: minio
    hostname: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio-secret
      - MINIO_DEFAULT_BUCKETS=graft-primary
    networks:
      basic-net:
        ipv4_address: 10.20.20.12

networks:
  basic-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.20.0/24

volumes:
  minio_data:
