// This file is auto-generated by scripts/compile-ui-files.ts on 2025-07-02T14:34:58.700Z
// DO NOT EDIT THIS FILE MANUALLY
export const uiComponentsDependencies = {
  "aspect-ratio": {
    "thirdPartyLibs": [
      "radix-ui"
    ],
    "uiLibs": []
  },
  "alert-dialog": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "class-variance-authority"
    ],
    "uiLibs": [
      "button"
    ]
  },
  "pagination": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-icons",
      "radix-ui",
      "class-variance-authority"
    ],
    "uiLibs": [
      "button"
    ]
  },
  "tabs": {
    "thirdPartyLibs": [
      "react",
      "radix-ui"
    ],
    "uiLibs": []
  },
  "card": {
    "thirdPartyLibs": [
      "react"
    ],
    "uiLibs": []
  },
  "slider": {
    "thirdPartyLibs": [
      "react",
      "radix-ui"
    ],
    "uiLibs": []
  },
  "popover": {
    "thirdPartyLibs": [
      "react",
      "radix-ui"
    ],
    "uiLibs": []
  },
  "progress": {
    "thirdPartyLibs": [
      "react",
      "radix-ui"
    ],
    "uiLibs": []
  },
  "toaster": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "class-variance-authority",
      "@radix-ui/react-icons"
    ],
    "uiLibs": [
      "toast"
    ]
  },
  "input-otp": {
    "thirdPartyLibs": [
      "react",
      "input-otp",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "chart": {
    "thirdPartyLibs": [
      "react",
      "recharts"
    ],
    "uiLibs": []
  },
  "hover-card": {
    "thirdPartyLibs": [
      "react",
      "radix-ui"
    ],
    "uiLibs": []
  },
  "sheet": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "class-variance-authority",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "scroll-area": {
    "thirdPartyLibs": [
      "react",
      "radix-ui"
    ],
    "uiLibs": []
  },
  "resizable": {
    "thirdPartyLibs": [
      "react-resizable-panels",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "label": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "class-variance-authority"
    ],
    "uiLibs": []
  },
  "sonner": {
    "thirdPartyLibs": [
      "next-themes",
      "sonner"
    ],
    "uiLibs": []
  },
  "navigation-menu": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "class-variance-authority",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "accordion": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "drawer": {
    "thirdPartyLibs": [
      "react",
      "vaul"
    ],
    "uiLibs": []
  },
  "tooltip": {
    "thirdPartyLibs": [
      "react",
      "radix-ui"
    ],
    "uiLibs": []
  },
  "alert": {
    "thirdPartyLibs": [
      "react",
      "class-variance-authority"
    ],
    "uiLibs": []
  },
  "use-toast": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "class-variance-authority",
      "@radix-ui/react-icons"
    ],
    "uiLibs": [
      "toast"
    ]
  },
  "switch": {
    "thirdPartyLibs": [
      "react",
      "radix-ui"
    ],
    "uiLibs": []
  },
  "calendar": {
    "thirdPartyLibs": [
      "react",
      "react-day-picker",
      "@radix-ui/react-icons",
      "radix-ui",
      "class-variance-authority"
    ],
    "uiLibs": [
      "button"
    ]
  },
  "breadcrumb": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "radio-group": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "command": {
    "thirdPartyLibs": [
      "@radix-ui/react-icons",
      "cmdk",
      "react",
      "radix-ui"
    ],
    "uiLibs": [
      "dialog"
    ]
  },
  "toggle-group": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "class-variance-authority"
    ],
    "uiLibs": [
      "toggle"
    ]
  },
  "avatar": {
    "thirdPartyLibs": [
      "react",
      "radix-ui"
    ],
    "uiLibs": []
  },
  "menubar": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "dialog": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "badge": {
    "thirdPartyLibs": [
      "react",
      "class-variance-authority"
    ],
    "uiLibs": []
  },
  "sidebar": {
    "thirdPartyLibs": [
      "react",
      "@radix-ui/react-icons",
      "class-variance-authority",
      "radix-ui"
    ],
    "uiLibs": [
      "button",
      "input",
      "separator",
      "sheet",
      "skeleton",
      "tooltip"
    ]
  },
  "table": {
    "thirdPartyLibs": [
      "react"
    ],
    "uiLibs": []
  },
  "separator": {
    "thirdPartyLibs": [
      "react",
      "radix-ui"
    ],
    "uiLibs": []
  },
  "button": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "class-variance-authority"
    ],
    "uiLibs": []
  },
  "toggle": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "class-variance-authority"
    ],
    "uiLibs": []
  },
  "toast": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "class-variance-authority",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "checkbox": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "collapsible": {
    "thirdPartyLibs": [
      "radix-ui"
    ],
    "uiLibs": []
  },
  "dropdown-menu": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "select": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "textarea": {
    "thirdPartyLibs": [
      "react"
    ],
    "uiLibs": []
  },
  "input": {
    "thirdPartyLibs": [
      "react"
    ],
    "uiLibs": []
  },
  "skeleton": {
    "thirdPartyLibs": [],
    "uiLibs": []
  },
  "context-menu": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "@radix-ui/react-icons"
    ],
    "uiLibs": []
  },
  "form": {
    "thirdPartyLibs": [
      "react",
      "radix-ui",
      "react-hook-form",
      "class-variance-authority"
    ],
    "uiLibs": [
      "label"
    ]
  },
  "carousel": {
    "thirdPartyLibs": [
      "react",
      "embla-carousel-react",
      "@radix-ui/react-icons",
      "radix-ui",
      "class-variance-authority"
    ],
    "uiLibs": [
      "button"
    ]
  }
}